// _nvngx.dll: the NGX core OptiScaler's NVNGXProxy loads, on a machine that has no NGX core.
//
// It has two jobs, and the second one arrived with wilsjo2's fork.
//
// 1. THE PARAMETER BLOCK. OptiScaler's DLSS-NR pass needs one to drive the model through, and it will
//    only take the *core's* capability block: `NVNGXProxy::InitDx12(device)` and then
//    `D3D12_GetCapabilityParameters()`, and it gives up if either declines. On NVIDIA the block
//    carries the snippet's own callbacks, which is why a freshly allocated one will not do.
//
// 2. FEATURE 18 ITSELF. From 0.8.1 on, wilsjo2's fork loads no forwarder at all -- its INSTALL-DLSSNR.md
//    says "No NR helper DLL is required; remove the obsolete nvngx.dll_dlssnr.dll when upgrading" --
//    and drives the model straight through this core. Verified against the v0.8.4 tree at
//    artifacts/ref/wilsjo2-OptiScaler-DLSSNR-PreSR-Multipass (tag v0.8.4, HEAD 8802b2b):
//
//      dlssnr/DlssNr_Proxy.cpp:154   D3D12_GetCapabilityParameters()(&state.params)   -- ownership to the caller
//      dlssnr/DlssNr_Proxy.cpp:174   SetCreationParameters(state.params, ...)         -- the DLSSNR.* keys
//      dlssnr/DlssNr_Proxy.cpp:177   D3D12_CreateFeature()(cmdList, (NVSDK_NGX_Feature) 18,
//                                                          state.params, &state.feature)
//      dlssnr/DlssNr_Proxy.cpp:280   D3D12_EvaluateFeature()(cmdList, state.feature, params, nullptr)
//      dlssnr/DlssNr_Proxy.cpp:36-47 D3D12_ReleaseFeature()(state.feature), then D3D12_DestroyParameters()
//
//    and on Vulkan, dlssnr/DlssNrFeature_Vk_Model.cpp:109 VULKAN_CreateFeature1(device, cmd, 18, ...),
//    :174 VULKAN_EvaluateFeature(cmd, feature, params, nullptr), :63-67 ReleaseFeature then
//    DestroyParameters.
//
//    Two things about create are not optional. `DlssNr_Proxy.cpp:180` falls back to
//    `DlssNr_CompatibilityRuntime` -- which LoadLibrary's NVIDIA's own nvngx_dlssnr.dll -- when and only
//    when create fails AND leaves the handle null, so our create must return Success with a non-null
//    handle or an AMD machine starts loading an NVIDIA runtime. And `DlssNrFeature_Vk_Model.cpp:111-126`
//    rejects the whole pass if two live handles share a pointer OR an `NVSDK_NGX_Handle::Id`, because
//    identical-profile passes still need independent temporal histories. Both are honoured below.
//
// What it must NOT do is make OptiScaler believe real DLSS is available. It does not, and cannot --
// see the note on DLSS gating at the bottom of this file.
//
// The exports are the 50 names NVNGXProxy::InitNVNGX resolves:
//   grep -o '"NVSDK_NGX_[A-Za-z0-9_]*"' proxies/NVNGX_Proxy.h | sort -u
// and their signatures are that header's own typedefs, which are what OptiScaler casts our
// GetProcAddress results to.

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <d3d12.h>

#include "nr_dlssnr_model.hpp"
#include "nr_ngx_abi.hpp"
#include "nr_pe_config.hpp"
#include "nr_pe_crash.hpp"
#include "nr_pe_log.hpp"
#include "nr_pe_optifix.hpp"

#include <cstring>
#include <map>
#include <mutex>
#include <set>
#include <string>

extern "C" void nr_vk_load(void);   // generated by the build; see windows/build/build_optiscaler_nr.sh

namespace {

// One parameter, type-tagged, with the same cross-type conversion OptiScaler's own NVNGX_Parameter
// does (NVNGX_Parameter.h, `struct Parameter`): a value written as a uint reads back as a float, and
// so on, because games and OptiScaler disagree constantly about which typed accessor a given key
// wants. Resources and void* are one family and never convert to a number except through the 64-bit
// accessor, which is how NGX itself is driven.
struct Value {
    enum class Kind { None, ULL, F, D, UI, I, Ptr } kind = Kind::None;
    unsigned long long ull = 0;
    float f = 0.0f;
    double d = 0.0;
    unsigned int ui = 0;
    int i = 0;
    void* ptr = nullptr;

    bool is_pointer() const { return kind == Kind::Ptr; }

    template <typename T> bool number(T* out) const {
        switch (kind) {
            case Kind::ULL: *out = static_cast<T>(ull); return true;
            case Kind::F:   *out = static_cast<T>(f);   return true;
            case Kind::D:   *out = static_cast<T>(d);   return true;
            case Kind::UI:  *out = static_cast<T>(ui);  return true;
            case Kind::I:   *out = static_cast<T>(i);   return true;
            default: return false;
        }
    }
};

// The block itself.
//
// Not a C++ class deriving from NVSDK_NGX_Parameter, because the compiler that lays such a class out
// here is GCC and every caller is MSVC, and the two disagree about where overloaded virtuals go. The
// vtable is built by hand in MSVC's order (nr_ngx_abi.hpp has the table and the evidence) and hung off
// the first word of the object, which is the whole of the object's ABI.
class Parameters {
  public:
    Parameters();

    const NVSDK_NGX_ParameterVtbl* vtbl;   // MUST be the first member: it is the object, to a caller.

    NVSDK_NGX_Parameter* as_parameter() { return reinterpret_cast<NVSDK_NGX_Parameter*>(this); }

    void set_ull(const char* name, unsigned long long v) { auto& s = slot(name); s.kind = Value::Kind::ULL; s.ull = v; }
    void set_float(const char* name, float v)            { auto& s = slot(name); s.kind = Value::Kind::F;   s.f = v; }
    void set_double(const char* name, double v)          { auto& s = slot(name); s.kind = Value::Kind::D;   s.d = v; }
    void set_uint(const char* name, unsigned int v)      { auto& s = slot(name); s.kind = Value::Kind::UI;  s.ui = v; }
    void set_int(const char* name, int v)                { auto& s = slot(name); s.kind = Value::Kind::I;   s.i = v; }
    void set_ptr(const char* name, void* v) {
        auto& s = slot(name);
        s.kind = Value::Kind::Ptr;
        s.ptr = v;
        s.ull = reinterpret_cast<unsigned long long>(v);
    }

    NVSDK_NGX_Result get_ull(const char* name, unsigned long long* out) const {
        const Value* v = find(name);
        if (!v || !out) return NVSDK_NGX_Result_Fail;
        // A pointer written through the 64-bit setter has to come back through it: that is how every
        // resource in the NGX surface travels.
        if (v->is_pointer()) { *out = reinterpret_cast<unsigned long long>(v->ptr); return NVSDK_NGX_Result_Success; }
        return v->number(out) ? NVSDK_NGX_Result_Success : NVSDK_NGX_Result_Fail;
    }
    NVSDK_NGX_Result get_float(const char* name, float* out) const   { return number(name, out); }
    NVSDK_NGX_Result get_double(const char* name, double* out) const { return number(name, out); }
    NVSDK_NGX_Result get_uint(const char* name, unsigned int* out) const { return number(name, out); }
    NVSDK_NGX_Result get_int(const char* name, int* out) const       { return number(name, out); }
    NVSDK_NGX_Result get_ptr(const char* name, void** out) const {
        const Value* v = find(name);
        if (!v || !out) return NVSDK_NGX_Result_Fail;
        if (!v->is_pointer()) return NVSDK_NGX_Result_Fail;
        *out = v->ptr;
        return NVSDK_NGX_Result_Success;
    }

    void reset() {
        std::lock_guard<std::mutex> guard(lock_);
        values_.clear();
    }

  private:
    Value& slot(const char* name) {
        std::lock_guard<std::mutex> guard(lock_);
        return values_[name ? name : ""];
    }
    const Value* find(const char* name) const {
        std::lock_guard<std::mutex> guard(lock_);
        auto it = values_.find(name ? name : "");
        return it == values_.end() ? nullptr : &it->second;
    }
    template <typename T> NVSDK_NGX_Result number(const char* name, T* out) const {
        const Value* v = find(name);
        if (!v || !out) return NVSDK_NGX_Result_Fail;
        return v->number(out) ? NVSDK_NGX_Result_Success : NVSDK_NGX_Result_Fail;
    }

    mutable std::mutex lock_;
    std::map<std::string, Value> values_;
};

// The thunks. One per slot, in MSVC's order, each recovering the object from the block pointer the
// caller has: they are the same address, because `vtbl` is the first member.
namespace vt {

Parameters* self(NVSDK_NGX_Parameter* p) { return reinterpret_cast<Parameters*>(p); }
const Parameters* self(const NVSDK_NGX_Parameter* p) { return reinterpret_cast<const Parameters*>(p); }

void NR_NGX_MSABI SetVoidPtr(NVSDK_NGX_Parameter* p, const char* n, void* v)           { self(p)->set_ptr(n, v); }
void NR_NGX_MSABI SetD3D12(NVSDK_NGX_Parameter* p, const char* n, ID3D12Resource* v)   { self(p)->set_ptr(n, v); }
void NR_NGX_MSABI SetD3D11(NVSDK_NGX_Parameter* p, const char* n, ID3D11Resource* v)   { self(p)->set_ptr(n, v); }
void NR_NGX_MSABI SetInt(NVSDK_NGX_Parameter* p, const char* n, int v)                 { self(p)->set_int(n, v); }
void NR_NGX_MSABI SetUInt(NVSDK_NGX_Parameter* p, const char* n, unsigned int v)       { self(p)->set_uint(n, v); }
void NR_NGX_MSABI SetDouble(NVSDK_NGX_Parameter* p, const char* n, double v)           { self(p)->set_double(n, v); }
void NR_NGX_MSABI SetFloat(NVSDK_NGX_Parameter* p, const char* n, float v)             { self(p)->set_float(n, v); }
void NR_NGX_MSABI SetULL(NVSDK_NGX_Parameter* p, const char* n, unsigned long long v)  { self(p)->set_ull(n, v); }

NVSDK_NGX_Result NR_NGX_MSABI GetVoidPtr(const NVSDK_NGX_Parameter* p, const char* n, void** v) { return self(p)->get_ptr(n, v); }
NVSDK_NGX_Result NR_NGX_MSABI GetD3D12(const NVSDK_NGX_Parameter* p, const char* n, ID3D12Resource** v) { return self(p)->get_ptr(n, reinterpret_cast<void**>(v)); }
NVSDK_NGX_Result NR_NGX_MSABI GetD3D11(const NVSDK_NGX_Parameter* p, const char* n, ID3D11Resource** v) { return self(p)->get_ptr(n, reinterpret_cast<void**>(v)); }
NVSDK_NGX_Result NR_NGX_MSABI GetInt(const NVSDK_NGX_Parameter* p, const char* n, int* v)               { return self(p)->get_int(n, v); }
NVSDK_NGX_Result NR_NGX_MSABI GetUInt(const NVSDK_NGX_Parameter* p, const char* n, unsigned int* v)     { return self(p)->get_uint(n, v); }
NVSDK_NGX_Result NR_NGX_MSABI GetDouble(const NVSDK_NGX_Parameter* p, const char* n, double* v)         { return self(p)->get_double(n, v); }
NVSDK_NGX_Result NR_NGX_MSABI GetFloat(const NVSDK_NGX_Parameter* p, const char* n, float* v)           { return self(p)->get_float(n, v); }
NVSDK_NGX_Result NR_NGX_MSABI GetULL(const NVSDK_NGX_Parameter* p, const char* n, unsigned long long* v){ return self(p)->get_ull(n, v); }

void NR_NGX_MSABI Reset(NVSDK_NGX_Parameter* p) { self(p)->reset(); }

const NVSDK_NGX_ParameterVtbl kTable = {
    SetVoidPtr, SetD3D12, SetD3D11, SetInt, SetUInt, SetDouble, SetFloat, SetULL,
    GetVoidPtr, GetD3D12, GetD3D11, GetInt, GetUInt, GetDouble, GetFloat, GetULL,
    Reset,
};

}  // namespace vt

Parameters::Parameters() : vtbl(&vt::kTable) {}

// The capability defaults.
//
// These say "this core runs no features". The names are the ones NVIDIA's own capability block
// publishes and the ones OptiScaler reads back (NVNGX_Parameter.cpp InitNGXParameters uses the same
// macros: SuperSampling.Available, .NeedsUpdatedDriver, .MinDriverVersionMajor/Minor,
// .FeatureInitResult; the denoiser family is spelled SuperSamplingDenoising.*).
//
// They are also, on the path a game sees, overwritten a microsecond later -- see the DLSS gating note
// at the bottom. They matter for the path OptiScaler's *own* DLSS-NR code takes, which reads this
// block directly without calling InitNGXParameters on it first.
void populate_capabilities(Parameters* p) {
    p->set_uint("SuperSampling.Available", 0u);
    p->set_uint("SuperSampling.NeedsUpdatedDriver", 0u);
    p->set_uint("SuperSampling.MinDriverVersionMajor", 0u);
    p->set_uint("SuperSampling.MinDriverVersionMinor", 0u);
    p->set_uint("SuperSampling.FeatureInitResult",
           static_cast<unsigned int>(NVSDK_NGX_Result_FAIL_FeatureNotSupported));

    p->set_uint("SuperSamplingDenoising.Available", 0u);
    p->set_uint("SuperSamplingDenoising.NeedsUpdatedDriver", 0u);
    p->set_uint("SuperSamplingDenoising.MinDriverVersionMajor", 0u);
    p->set_uint("SuperSamplingDenoising.MinDriverVersionMinor", 0u);
    p->set_uint("SuperSamplingDenoising.FeatureInitResult",
           static_cast<unsigned int>(NVSDK_NGX_Result_FAIL_FeatureNotSupported));

    p->set_uint("FrameGeneration.Available", 0u);
    p->set_uint("FrameInterpolation.Available", 0u);

    p->set_uint("CreationNodeMask", 1u);
    p->set_uint("VisibilityNodeMask", 1u);

    // There is no DLSSNR.Available anywhere in OptiScaler -- nothing reads such a key, so nothing is
    // written for it. (grep -rn "DLSSNR.Available" over the reference tree: no hits.) Whether the NR
    // pass runs is decided by Config [DlssNr] Enabled plus the two DLLs being present, never by a
    // capability bit.
}

Parameters* new_block(bool capability) {
    auto* p = new Parameters();
    if (capability) populate_capabilities(p);
    return p;
}

std::mutex g_lock;
bool g_d3d11_inited = false;
bool g_d3d12_inited = false;
bool g_vulkan_inited = false;

NVSDK_NGX_Result allocate(NVSDK_NGX_Parameter** out, bool capability) {
    if (!out) return NVSDK_NGX_Result_FAIL_InvalidParameter;
    *out = new_block(capability)->as_parameter();
    return NVSDK_NGX_Result_Success;
}

NVSDK_NGX_Result destroy(NVSDK_NGX_Parameter* params) {
    delete reinterpret_cast<Parameters*>(params);
    return NVSDK_NGX_Result_Success;
}

// A number large enough that nobody sizes a heap from it and finds it short, and small enough that a
// caller who really does allocate it is not asking for a gigabyte. Nothing on this side ever uses a
// scratch buffer: our network owns its own memory.
constexpr size_t kScratchBytes = 4u * 1024u * 1024u;

// ---------------------------------------------------------------------------------------------
// Feature 18: Neural Rendering.
// ---------------------------------------------------------------------------------------------

// Reading the block, which on this path is our own object.
//
// DlssNr_Proxy.cpp:154 takes the block from D3D12_GetCapabilityParameters, so the pointer handed to
// CreateFeature and EvaluateFeature is a Parameters* that left new_block() a moment earlier. It is
// recognised by its vtable pointer and read through std::map directly -- no call back out through the
// vtable and no chance of a slot mismatch on the way in. A block from anywhere else (a game's own, a
// future OptiScaler that allocates its own) is still read, through the published interface, which is
// correct because nr_ngx_abi.hpp lays that interface out in MSVC's order.
class Reader {
  public:
    explicit Reader(const NVSDK_NGX_Parameter* p)
        : block_(p), mine_(p && p->vtbl == &vt::kTable ? reinterpret_cast<const Parameters*>(p) : nullptr) {}

    bool valid() const { return block_ != nullptr; }
    bool is_ours() const { return mine_ != nullptr; }

    bool uint(const char* name, unsigned int* out) const {
        if (!block_) return false;
        return (mine_ ? mine_->get_uint(name, out) : block_->Get(name, out)) == NVSDK_NGX_Result_Success;
    }
    bool real(const char* name, float* out) const {
        if (!block_) return false;
        return (mine_ ? mine_->get_float(name, out) : block_->Get(name, out)) == NVSDK_NGX_Result_Success;
    }
    // Every resource in this surface is written either as Set(void*) (Vulkan, and OptiScaler's own
    // note that NVIDIA's table "ignores typed ID3D12Resource* setters") or as Set(ID3D12Resource*)
    // (the D3D12 path). Our block keeps both in one family, so one read answers both; a foreign block
    // is asked through the void* getter and then the resource getter.
    void* resource(const char* name) const {
        if (!block_) return nullptr;
        void* p = nullptr;
        if (mine_) return mine_->get_ptr(name, &p) == NVSDK_NGX_Result_Success ? p : nullptr;
        if (block_->Get(name, &p) == NVSDK_NGX_Result_Success) return p;
        ID3D12Resource* r = nullptr;
        if (block_->Get(name, &r) == NVSDK_NGX_Result_Success) return r;
        return nullptr;
    }

  private:
    const NVSDK_NGX_Parameter* block_;
    const Parameters* mine_;
};

// The six tuning controls, read over whatever the feature already holds so a key the caller left out
// keeps its create-time value. The reference writes all six at create AND at every evaluate
// (DlssNr_Proxy.cpp:67-72 and :272-277), so in practice every one is present every time.
//
// DLSSNR.SkinStructureStrength's -1 is "follow LocalStructure", not "off" -- DlssNr_Common.h:324 --
// and nr::Controls::skin_structure already means exactly that, so it passes through unmapped.
void read_controls(const Reader& r, nr::dlssnr::Controls6* c) {
    float f = 0.0f;
    unsigned int u = 0;
    if (r.real("DLSSNR.Intensity", &f)) c->intensity = f;
    if (r.uint("DLSSNR.Style", &u)) c->style = static_cast<int>(u);
    if (r.real("DLSSNR.LocalStructureStrength", &f)) c->local_structure = f;
    if (r.real("DLSSNR.LocalToneStrength", &f)) c->local_tone = f;
    if (r.real("DLSSNR.SkinStructureStrength", &f)) c->skin_structure = f;
    if (r.uint("DLSSNR.UseAutoMask", &u)) c->use_auto_mask = static_cast<int>(u);

    // Read and ignored, deliberately:
    //
    //   DLSSNR.GlobalToneStrength  the pinned DLL does not have it. A scan of nvngx_dlssnr.dll for
    //                              DLSSNR.* yields 61 names and this is not one of them
    //                              (DlssNr_Common.h:315-320), which is why wilsjo2 never writes it and
    //                              why the forwarder's dlssnr_call_set_extras drops it too.
    //   DLSSNR.UICorrection        our network has no UI-correction pass; the reference always writes
    //                              the model's own default 1u (DlssNr_Proxy.cpp:76).
    //   DLSSNR.ControlMask         always null on this path (:77); an external mask would take
    //                              precedence over UseAutoMask and there is never one to take.
    //   DLSSNR.UI / .UIAlpha / .Backbuffer and their twelve subrect keys -- all null and all zero
    //                              (:78-85). Nothing here has a UI pass to give them to.
}

// A live feature. The NVSDK_NGX_Handle is the FIRST member, so the pointer OptiScaler holds and the
// pointer we hold are the same address; `Id` is a process-wide counter because
// DlssNrFeature_Vk_Model.cpp:111-126 rejects the pass if two live handles share either one.
struct NgxFeature {
    NVSDK_NGX_Handle handle{};
    enum class Api { D3D12, Vulkan } api = Api::D3D12;
    nr::dlssnr::Feature* model = nullptr;
    // Non-null when this process also has the forwarder DLL loaded and the model lives over there;
    // see the delegation note below.
    void* foreign = nullptr;
    unsigned int width = 0;
    unsigned int height = 0;
    int preset = 0;
    int ui_correction = 1;
    nr::dlssnr::Controls6 controls;
};

std::mutex g_feature_lock;
unsigned int g_next_feature_id = 1;
std::set<NgxFeature*> g_features;

NgxFeature* live(const NVSDK_NGX_Handle* handle) {
    auto* f = reinterpret_cast<NgxFeature*>(const_cast<NVSDK_NGX_Handle*>(handle));
    return g_features.count(f) ? f : nullptr;
}

// ---------------------------------------------------------------------------------------------
// One Session per API in this process, even if both of our DLLs are loaded.
//
// windows/src/pe/nr_dlssnr_model.cpp keeps one nr::pe::Session per graphics API, which is what stops a
// re-created feature from re-uploading 300 MB of weights. Both nvngx.dll_dlssnr.dll and _nvngx.dll
// link that translation unit, so a process holding BOTH would hold two of those singletons and build
// two networks on one GPU.
//
// It cannot be assumed away in either direction: wilsjo2 >= 0.8.1 loads no forwarder and tells users
// to delete it (INSTALL-DLSSNR.md:13), so this core must carry its own model; Dagherbou's release
// loads the forwarder and never touches CreateFeature. But a host could do both, and the answer is
// cheap -- if nvngx.dll_dlssnr.dll is already in the module list, route through its C exports, which
// are the same code driving the session it already owns. GetModuleHandleW, never LoadLibrary: the
// question is "is it already here", not "make it be here".
struct Forwarder {
    using PFN_create = void* (*)(const wchar_t*, const wchar_t*, ID3D12Device*, ID3D12GraphicsCommandList*,
                                 void*, unsigned int, unsigned int, int, float, int, float, float, float,
                                 int, int);
    using PFN_evaluate = int (*)(ID3D12GraphicsCommandList*, void*, void*, ID3D12Resource*, ID3D12Resource*,
                                 ID3D12Resource*, ID3D12Resource*, unsigned int, unsigned int, unsigned int,
                                 unsigned int, unsigned int, unsigned int, unsigned int, unsigned int,
                                 unsigned int, unsigned int, int, int, float, int, float, float, float, int,
                                 float, float);
    using PFN_release = void (*)(void*);
    using PFN_vk_init = int (*)(const wchar_t*, const wchar_t*, void*, void*, void*, int);
    using PFN_vk_create = void* (*)(void*, void*, unsigned int, unsigned int, int, float, int, float, float,
                                    float, int, int);
    using PFN_vk_evaluate = int (*)(void*, void*, void*, void*, void*, void*, void*, unsigned int,
                                    unsigned int, unsigned int, unsigned int, unsigned int, unsigned int,
                                    unsigned int, unsigned int, unsigned int, unsigned int, int, int, float,
                                    int, float, float, float, int, float, float);
    using PFN_vk_release = void (*)(void*);

    PFN_create create = nullptr;
    PFN_evaluate evaluate = nullptr;
    PFN_release release = nullptr;
    PFN_vk_init vk_init = nullptr;
    PFN_vk_create vk_create = nullptr;
    PFN_vk_evaluate vk_evaluate = nullptr;
    PFN_vk_release vk_release = nullptr;

    bool d3d12() const { return create && evaluate && release; }
    bool vulkan() const { return vk_init && vk_create && vk_evaluate && vk_release; }
};

const Forwarder& forwarder() {
    static Forwarder resolved = [] {
        Forwarder f;
        HMODULE m = GetModuleHandleW(L"nvngx.dll_dlssnr.dll");
        if (!m) return f;
        auto sym = [m](const char* n) { return reinterpret_cast<void*>(GetProcAddress(m, n)); };
        f.create = reinterpret_cast<Forwarder::PFN_create>(sym("dlssnr_call_create"));
        f.evaluate = reinterpret_cast<Forwarder::PFN_evaluate>(sym("dlssnr_call_evaluate_v2"));
        f.release = reinterpret_cast<Forwarder::PFN_release>(sym("dlssnr_call_release"));
        f.vk_init = reinterpret_cast<Forwarder::PFN_vk_init>(sym("dlssnr_vk_init"));
        f.vk_create = reinterpret_cast<Forwarder::PFN_vk_create>(sym("dlssnr_vk_create"));
        f.vk_evaluate = reinterpret_cast<Forwarder::PFN_vk_evaluate>(sym("dlssnr_vk_evaluate_v2"));
        f.vk_release = reinterpret_cast<Forwarder::PFN_vk_release>(sym("dlssnr_vk_release"));
        nr::pe::log("[nr] _nvngx.dll: nvngx.dll_dlssnr.dll is already loaded in this process; feature 18 "
                    "will run on its session rather than starting a second network (D3D12 %s, Vulkan %s)",
                    f.d3d12() ? "yes" : "no", f.vulkan() ? "yes" : "no");
        return f;
    }();
    return resolved;
}

// The Vulkan handles the game gave us at NVSDK_NGX_VULKAN_Init*. VULKAN_CreateFeature1 carries only the
// device, and the model needs the instance and the physical device too, so they are kept from init.
void* g_vk_instance = nullptr;
void* g_vk_physical = nullptr;
void* g_vk_device = nullptr;
bool g_vk_model_inited = false;

// Called from every NVSDK_NGX_VULKAN_Init* variant, all of which carry the three handles, with g_lock
// held. The model is initialised as soon as all three are known, so its "no queue is known" decline
// lands in the log at init -- where a user can act on it -- rather than at the first frame.
void note_vulkan(NrVkInstance instance, NrVkPhysicalDevice physical, NrVkDevice device) {
    if (instance) g_vk_instance = instance;
    if (physical) g_vk_physical = physical;
    if (device) g_vk_device = device;
    if (g_vk_model_inited || !g_vk_instance || !g_vk_physical || !g_vk_device) return;
    const Forwarder& fwd = forwarder();
    const int result = fwd.vulkan() ? fwd.vk_init(nullptr, nullptr, g_vk_instance, g_vk_physical,
                                                  g_vk_device, 0)
                                    : nr::dlssnr::vk_init(g_vk_instance, g_vk_physical, g_vk_device);
    g_vk_model_inited = result == static_cast<int>(NVSDK_NGX_Result_Success);
}

// VULKAN_CreateFeature1's own device, for the case where init declined and the handles have since
// become answerable (the queue watcher can learn a queue after NGX was initialised).
bool ensure_vulkan_model(NrVkDevice device) {
    std::lock_guard<std::mutex> guard(g_lock);
    if (g_vk_model_inited) return true;
    note_vulkan(nullptr, nullptr, device);
    return g_vk_model_inited;
}

// NVSDK_NGX_FeatureDiscoveryInfo's second field, read positionally so no SDK struct has to be
// declared here: { NVSDK_NGX_Version SDKVersion; NVSDK_NGX_Feature FeatureID; ... } and both are
// int-sized enums (external/nvngx_dlss_sdk/nvsdk_ngx_defs.h:490-497).
int discovery_feature_id(const void* info) {
    return info ? reinterpret_cast<const int*>(info)[1] : 0;
}

// NVSDK_NGX_FeatureRequirement is { NVSDK_NGX_Feature_Support_Result FeatureSupported; unsigned int
// MinHWArchitecture; char MinOSVersion[255]; } -- defs.h:499-509. Zero in the first field IS
// "Supported" (defs.h:402), so "supported, no minimum architecture, no minimum OS" is nine zero bytes.
void write_requirement(void* out, bool supported) {
    if (!out) return;
    auto* words = static_cast<unsigned int*>(out);
    words[0] = supported ? 0u : static_cast<unsigned int>(16);   // 16 = NotImplemented
    words[1] = 0u;
    static_cast<char*>(out)[8] = '\0';
}

}  // namespace

#define NR_EXPORT extern "C" __declspec(dllexport)

// ---------------------------------------------------------------------------------------------
// Direct3D 11
// ---------------------------------------------------------------------------------------------

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_Init(unsigned long long, const wchar_t*, ID3D11Device*,
                                                const void*, NVSDK_NGX_Version) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_d3d11_inited = true;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_Init_Ext(unsigned long long, const wchar_t*, ID3D11Device*,
                                                    NVSDK_NGX_Version, const void*) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_d3d11_inited = true;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_Init_ProjectID(const char*, NVSDK_NGX_EngineType, const char*,
                                                          const wchar_t*, ID3D11Device*,
                                                          NVSDK_NGX_Version, const void*) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_d3d11_inited = true;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_Shutdown(void) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_d3d11_inited = false;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_Shutdown1(ID3D11Device*) {
    return NVSDK_NGX_D3D11_Shutdown();
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_GetParameters(NVSDK_NGX_Parameter** out) {
    return allocate(out, true);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_AllocateParameters(NVSDK_NGX_Parameter** out) {
    return allocate(out, false);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_GetCapabilityParameters(NVSDK_NGX_Parameter** out) {
    return allocate(out, true);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_DestroyParameters(NVSDK_NGX_Parameter* params) {
    return destroy(params);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_GetScratchBufferSize(NVSDK_NGX_Feature, const NVSDK_NGX_Parameter*,
                                                                size_t* out) {
    if (!out) return NVSDK_NGX_Result_FAIL_InvalidParameter;
    *out = kScratchBytes;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_CreateFeature(ID3D11DeviceContext*, NVSDK_NGX_Feature,
                                                         NVSDK_NGX_Parameter*, NVSDK_NGX_Handle** out) {
    if (out) *out = nullptr;
    return NVSDK_NGX_Result_FAIL_FeatureNotSupported;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_ReleaseFeature(NVSDK_NGX_Handle*) {
    return NVSDK_NGX_Result_FAIL_FeatureNotFound;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_EvaluateFeature(ID3D11DeviceContext*, const NVSDK_NGX_Handle*,
                                                           const NVSDK_NGX_Parameter*, void*) {
    return NVSDK_NGX_Result_FAIL_FeatureNotFound;
}

// The discovery query. OutSupported is an NVSDK_NGX_FeatureRequirement: a FeatureSupported bit field,
// then the minimum architecture, then the minimum OS version, then a path. Zeroing the first three
// words and reporting FeatureNotSupported is the honest answer for every feature this core carries,
// which is none. Written as three unsigned ints so no SDK struct has to be declared here; the caller
// always supplies the full struct.
NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D11_GetFeatureRequirements(IDXGIAdapter*, const void*,
                                                                  void* OutSupported) {
    if (OutSupported) std::memset(OutSupported, 0, 3 * sizeof(unsigned int));
    return NVSDK_NGX_Result_FAIL_FeatureNotSupported;
}

// ---------------------------------------------------------------------------------------------
// Direct3D 12 -- the one path that matters; everything DLSS-NR does goes through these.
// ---------------------------------------------------------------------------------------------

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_Init(unsigned long long, const wchar_t*, ID3D12Device*,
                                                const void*, NVSDK_NGX_Version) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_d3d12_inited = true;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_Init_Ext(unsigned long long, const wchar_t*, ID3D12Device*,
                                                    NVSDK_NGX_Version, const void*) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_d3d12_inited = true;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_Init_ProjectID(const char*, NVSDK_NGX_EngineType, const char*,
                                                          const wchar_t*, ID3D12Device*,
                                                          NVSDK_NGX_Version, const void*) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_d3d12_inited = true;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_Shutdown(void) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_d3d12_inited = false;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_Shutdown1(ID3D12Device*) {
    return NVSDK_NGX_D3D12_Shutdown();
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_GetParameters(NVSDK_NGX_Parameter** out) {
    return allocate(out, true);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_AllocateParameters(NVSDK_NGX_Parameter** out) {
    return allocate(out, false);
}

// The one OptiScaler's DLSS-NR pass needs. Every call returns a fresh block, which is the SDK's
// contract ("the lifetime of this map is managed by the calling application with
// DestroyParameters"), and OptiScaler tags it NVDynamic and frees it through our DestroyParameters.
NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_GetCapabilityParameters(NVSDK_NGX_Parameter** out) {
    return allocate(out, true);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_DestroyParameters(NVSDK_NGX_Parameter* params) {
    return destroy(params);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_GetScratchBufferSize(NVSDK_NGX_Feature, const NVSDK_NGX_Parameter*,
                                                                size_t* out) {
    if (!out) return NVSDK_NGX_Result_FAIL_InvalidParameter;
    // Nothing on this side ever uses a scratch buffer -- the network owns its own memory -- and
    // wilsjo2 never asks: grep GetScratchBufferSize over the v0.8.4 tree has no hit in dlssnr/ or
    // shaders/dlssnr/. The answer stays the same small number for every feature, 18 included.
    *out = kScratchBytes;
    return NVSDK_NGX_Result_Success;
}

// Feature 18 (Neural Rendering) is built here; every other id is still declined. This is the seam
// wilsjo2 >= 0.8.1 uses -- see the note at the top of this file -- and the two rules it imposes are
// that success must carry a non-null handle (or DlssNr_Proxy.cpp:180 goes looking for NVIDIA's own
// nvngx_dlssnr.dll) and that no two live handles may share a pointer or an Id.
//
// The extent and the controls are read from the block the caller filled with SetCreationParameters
// (DlssNr_Proxy.cpp:55-87). Nothing is recorded into `cmd`: NGX builds its feature on the command
// list, whereas nr::Runtime is built on the session's own queue on a background thread. The caller
// already allows for that -- it returns without evaluating after a create and waits a submission
// epoch (DlssNr_Proxy.cpp:210-213) -- and the first frames pass through unenhanced either way.
NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_CreateFeature(ID3D12GraphicsCommandList* cmd,
                                                         NVSDK_NGX_Feature featureId,
                                                         NVSDK_NGX_Parameter* params,
                                                         NVSDK_NGX_Handle** out) {
    if (out) *out = nullptr;
    if (featureId != NVSDK_NGX_Feature_NeuralRendering) return NVSDK_NGX_Result_FAIL_FeatureNotSupported;
    if (!cmd || !out) return NVSDK_NGX_Result_FAIL_InvalidParameter;

    const Reader r(params);
    unsigned int width = 0, height = 0, preset = 0, ui_correction = 1;
    r.uint("DLSSNR.Width", &width);
    r.uint("DLSSNR.Height", &height);
    r.uint("DLSSNR.Hint.Render.Preset", &preset);
    r.uint("DLSSNR.UICorrection", &ui_correction);
    nr::dlssnr::Controls6 controls;
    read_controls(r, &controls);
    if (width == 0 || height == 0) {
        nr::pe::log("[nr] CreateFeature(18): the block carries no DLSSNR.Width/Height");
        return NVSDK_NGX_Result_FAIL_InvalidParameter;
    }

    ID3D12Device* device = nullptr;
    if (FAILED(cmd->GetDevice(IID_PPV_ARGS(&device))) || !device) {
        nr::pe::log("[nr] CreateFeature(18): the command list belongs to no D3D12 device");
        return NVSDK_NGX_Result_FAIL_PlatformError;
    }

    std::lock_guard<std::mutex> guard(g_feature_lock);
    auto* f = new NgxFeature();
    f->api = NgxFeature::Api::D3D12;
    f->width = width;
    f->height = height;
    f->preset = static_cast<int>(preset);
    f->ui_correction = static_cast<int>(ui_correction);
    f->controls = controls;

    int result = static_cast<int>(NVSDK_NGX_Result_Fail);
    const Forwarder& fwd = forwarder();
    if (fwd.d3d12()) {
        f->foreign = fwd.create(nullptr, nullptr, device, cmd, params, width, height, f->preset,
                                controls.intensity, controls.style, controls.local_structure,
                                controls.local_tone, controls.skin_structure, controls.use_auto_mask,
                                f->ui_correction);
        result = f->foreign ? static_cast<int>(NVSDK_NGX_Result_Success)
                            : static_cast<int>(NVSDK_NGX_Result_FAIL_UnableToInitializeFeature);
    } else {
        f->model = nr::dlssnr::create_d3d12(device, cmd, params, width, height, f->preset,
                                            f->ui_correction, controls, &result);
    }
    device->Release();

    if (!f->model && !f->foreign) {
        delete f;
        nr::pe::log("[nr] CreateFeature(18) declined 0x%X: %s", result, nr::dlssnr::last_error());
        return static_cast<NVSDK_NGX_Result>(result);
    }

    // Unique pointer and unique Id, both required: DlssNrFeature_Vk_Model.cpp:111-126 fails the whole
    // pass if a second create answers with either one already in use.
    f->handle.Id = g_next_feature_id++;
    g_features.insert(f);
    *out = &f->handle;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_ReleaseFeature(NVSDK_NGX_Handle* handle) {
    std::lock_guard<std::mutex> guard(g_feature_lock);
    NgxFeature* f = live(handle);
    if (!f) return NVSDK_NGX_Result_FAIL_FeatureNotFound;
    g_features.erase(f);
    if (f->foreign) forwarder().release(f->foreign);
    else if (f->model) nr::dlssnr::release_d3d12(f->model);
    delete f;
    return NVSDK_NGX_Result_Success;
}

// The progress callback is always null on this path (DlssNr_Proxy.cpp:281) and there is nothing to
// report progress on: the network either ran this frame or the seed copy did.
NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_EvaluateFeature(ID3D12GraphicsCommandList* cmd,
                                                           const NVSDK_NGX_Handle* handle,
                                                           const NVSDK_NGX_Parameter* params, void*) {
    std::unique_lock<std::mutex> guard(g_feature_lock);
    NgxFeature* f = live(handle);
    if (!f) return NVSDK_NGX_Result_FAIL_FeatureNotFound;
    if (!cmd) return NVSDK_NGX_Result_FAIL_InvalidParameter;

    const Reader r(params);
    // Everything below is re-read every call, because that is how the caller drives it: resources and
    // subrects change per frame, and the tuning is re-written at every evaluate as well as at create
    // (DlssNr_Proxy.cpp:236-277).
    unsigned int width = f->width, height = f->height;
    r.uint("DLSSNR.Width", &width);
    r.uint("DLSSNR.Height", &height);
    read_controls(r, &f->controls);
    const nr::dlssnr::Controls6 controls = f->controls;

    auto* color = static_cast<ID3D12Resource*>(r.resource("DLSSNR.Color"));
    auto* depth = static_cast<ID3D12Resource*>(r.resource("DLSSNR.Depth"));
    auto* motion = static_cast<ID3D12Resource*>(r.resource("DLSSNR.MVec"));
    auto* output = static_cast<ID3D12Resource*>(r.resource("DLSSNR.Output"));

    nr::dlssnr::Rect depth_rect{}, motion_rect{};
    r.uint("DLSSNR.DepthSubrectBaseX", &depth_rect.x);
    r.uint("DLSSNR.DepthSubrectBaseY", &depth_rect.y);
    r.uint("DLSSNR.DepthSubrectWidth", &depth_rect.width);
    r.uint("DLSSNR.DepthSubrectHeight", &depth_rect.height);
    r.uint("DLSSNR.MVecSubrectBaseX", &motion_rect.x);
    r.uint("DLSSNR.MVecSubrectBaseY", &motion_rect.y);
    r.uint("DLSSNR.MVecSubrectWidth", &motion_rect.width);
    r.uint("DLSSNR.MVecSubrectHeight", &motion_rect.height);

    // Colour and output carry subrects too, and the reference always writes base 0 with the working
    // extent (DlssNr_Proxy.cpp:249-256). The extent is taken; a non-zero base is not expressible -- the
    // pass reads the whole allocation -- and is said once rather than silently ignored, the same rule
    // the guides get inside apply_guide_subrect (nr_pe_session.cpp).
    unsigned int base = 0, sub = 0;
    if ((r.uint("DLSSNR.ColorSubrectBaseX", &base) && base) ||
        (r.uint("DLSSNR.ColorSubrectBaseY", &base) && base) ||
        (r.uint("DLSSNR.OutputSubrectBaseX", &base) && base) ||
        (r.uint("DLSSNR.OutputSubrectBaseY", &base) && base)) {
        static bool noted = false;
        if (!noted) {
            noted = true;
            nr::pe::log("[nr] EvaluateFeature(18): a colour or output subrect starts at a non-zero "
                        "origin; this pass can only express an origin-zero rect, so the whole "
                        "allocation is used");
        }
    }
    if (r.uint("DLSSNR.ColorSubrectWidth", &sub) && sub) width = sub;
    if (r.uint("DLSSNR.ColorSubrectHeight", &sub) && sub) height = sub;

    unsigned int depth_inverted = 0, reset = 0;
    r.uint("DLSSNR.DepthInverted", &depth_inverted);
    r.uint("DLSSNR.Reset", &reset);
    float mv_x = 1.0f, mv_y = 1.0f;
    r.real("DLSSNR.MVecScaleX", &mv_x);
    r.real("DLSSNR.MVecScaleY", &mv_y);

    nr::dlssnr::Feature* model = f->model;
    void* foreign = f->foreign;
    guard.unlock();   // the model has its own lock, and evaluate records a whole frame under it

    const int result =
        foreign ? forwarder().evaluate(cmd, foreign, const_cast<NVSDK_NGX_Parameter*>(params), color,
                                       depth, motion, output, width, height, depth_rect.width,
                                       depth_rect.height, motion_rect.width, motion_rect.height,
                                       depth_rect.x, depth_rect.y, motion_rect.x, motion_rect.y,
                                       static_cast<int>(depth_inverted), static_cast<int>(reset),
                                       controls.intensity, controls.style, controls.local_structure,
                                       controls.local_tone, controls.skin_structure,
                                       controls.use_auto_mask, mv_x, mv_y)
                : nr::dlssnr::evaluate_d3d12(cmd, model, const_cast<NVSDK_NGX_Parameter*>(params), color,
                                             depth, motion, output, width, height, depth_rect,
                                             motion_rect, static_cast<int>(depth_inverted),
                                             static_cast<int>(reset), controls, mv_x, mv_y);

    // The model answers 0 for "bad arguments", which is not an NGX code; everything else already is.
    if (result == 0) return NVSDK_NGX_Result_FAIL_InvalidParameter;
    return static_cast<NVSDK_NGX_Result>(result);
}

// wilsjo2 never calls this on the NR path (no GetFeatureRequirements anywhere under dlssnr/), but
// NVNGXProxy Detour-hooks the export if it exists, so it has to answer sensibly. Feature 18 is
// supported here; everything else is not.
NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_D3D12_GetFeatureRequirements(IDXGIAdapter*, const void* info,
                                                                  void* OutSupported) {
    const bool nr = discovery_feature_id(info) == NVSDK_NGX_Feature_NeuralRendering;
    write_requirement(OutSupported, nr);
    return nr ? NVSDK_NGX_Result_Success : NVSDK_NGX_Result_FAIL_FeatureNotSupported;
}

// ---------------------------------------------------------------------------------------------
// Vulkan
// ---------------------------------------------------------------------------------------------

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_Init(unsigned long long, const wchar_t*, NrVkInstance instance,
                                                 NrVkPhysicalDevice physical, NrVkDevice device, void*, void*,
                                                 const void*, NVSDK_NGX_Version) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_vulkan_inited = true;
    note_vulkan(instance, physical, device);
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_Init_Ext(unsigned long long, const wchar_t*, NrVkInstance instance,
                                                     NrVkPhysicalDevice physical, NrVkDevice device,
                                                     NVSDK_NGX_Version, const void*) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_vulkan_inited = true;
    note_vulkan(instance, physical, device);
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_Init_Ext2(unsigned long long, const wchar_t*, NrVkInstance instance,
                                                      NrVkPhysicalDevice physical, NrVkDevice device, void*,
                                                      void*, NVSDK_NGX_Version, const void*) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_vulkan_inited = true;
    note_vulkan(instance, physical, device);
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_Init_ProjectID(const char*, NVSDK_NGX_EngineType, const char*,
                                                           const wchar_t*, NrVkInstance instance,
                                                           NrVkPhysicalDevice physical, NrVkDevice device,
                                                           void*, void*, NVSDK_NGX_Version, const void*) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_vulkan_inited = true;
    note_vulkan(instance, physical, device);
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_Init_ProjectID_Ext(const char*, NVSDK_NGX_EngineType,
                                                               const char*, const wchar_t*,
                                                               NrVkInstance instance,
                                                               NrVkPhysicalDevice physical,
                                                               NrVkDevice device, void*, void*,
                                                               NVSDK_NGX_Version, const void*) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_vulkan_inited = true;
    note_vulkan(instance, physical, device);
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_Shutdown(void) {
    std::lock_guard<std::mutex> guard(g_lock);
    g_vulkan_inited = false;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_Shutdown1(NrVkDevice) {
    return NVSDK_NGX_VULKAN_Shutdown();
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_GetParameters(NVSDK_NGX_Parameter** out) {
    return allocate(out, true);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_AllocateParameters(NVSDK_NGX_Parameter** out) {
    return allocate(out, false);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_GetCapabilityParameters(NVSDK_NGX_Parameter** out) {
    return allocate(out, true);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_DestroyParameters(NVSDK_NGX_Parameter* params) {
    return destroy(params);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_GetScratchBufferSize(NVSDK_NGX_Feature,
                                                                 const NVSDK_NGX_Parameter*, size_t* out) {
    if (!out) return NVSDK_NGX_Result_FAIL_InvalidParameter;
    *out = kScratchBytes;
    return NVSDK_NGX_Result_Success;
}

// The Vulkan feature. wilsjo2 resolves CreateFeature1 and refuses to run without it
// (DlssNrFeature_Vk_Model.cpp:44-48 checks VULKAN_CreateFeature1, not CreateFeature), but the
// positional CreateFeature is published too and forwards here with the device we learned at init.
NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_CreateFeature1(NrVkDevice device, NrVkCommandBuffer cmd,
                                                           NVSDK_NGX_Feature featureId,
                                                           NVSDK_NGX_Parameter* params,
                                                           NVSDK_NGX_Handle** out) {
    if (out) *out = nullptr;
    if (featureId != NVSDK_NGX_Feature_NeuralRendering) return NVSDK_NGX_Result_FAIL_FeatureNotSupported;
    if (!cmd || !out) return NVSDK_NGX_Result_FAIL_InvalidParameter;

    // The model wants the instance and the physical device as well, and CreateFeature1 carries
    // neither; they were kept from NVSDK_NGX_VULKAN_Init*. A device arriving here that init never saw
    // is taken on trust for the retry, because it is the same device by construction -- OptiScaler
    // passes state.device, which is what it initialised us with.
    if (!ensure_vulkan_model(device)) return NVSDK_NGX_Result_FAIL_NotInitialized;

    const Reader r(params);
    unsigned int width = 0, height = 0, preset = 0, ui_correction = 1;
    r.uint("DLSSNR.Width", &width);
    r.uint("DLSSNR.Height", &height);
    r.uint("DLSSNR.Hint.Render.Preset", &preset);
    r.uint("DLSSNR.UICorrection", &ui_correction);
    nr::dlssnr::Controls6 controls;
    read_controls(r, &controls);
    if (width == 0 || height == 0) {
        nr::pe::log("[nr] VULKAN CreateFeature(18): the block carries no DLSSNR.Width/Height");
        return NVSDK_NGX_Result_FAIL_InvalidParameter;
    }

    std::lock_guard<std::mutex> guard(g_feature_lock);
    auto* f = new NgxFeature();
    f->api = NgxFeature::Api::Vulkan;
    f->width = width;
    f->height = height;
    f->preset = static_cast<int>(preset);
    f->ui_correction = static_cast<int>(ui_correction);
    f->controls = controls;

    int result = static_cast<int>(NVSDK_NGX_Result_Fail);
    const Forwarder& fwd = forwarder();
    if (fwd.vulkan()) {
        f->foreign = fwd.vk_create(cmd, params, width, height, f->preset, controls.intensity,
                                   controls.style, controls.local_structure, controls.local_tone,
                                   controls.skin_structure, controls.use_auto_mask, f->ui_correction);
        result = f->foreign ? static_cast<int>(NVSDK_NGX_Result_Success)
                            : static_cast<int>(NVSDK_NGX_Result_FAIL_NotInitialized);
    } else {
        f->model = nr::dlssnr::create_vk(cmd, params, width, height, f->preset, f->ui_correction,
                                         controls, &result);
    }

    if (!f->model && !f->foreign) {
        delete f;
        return static_cast<NVSDK_NGX_Result>(result);
    }

    f->handle.Id = g_next_feature_id++;
    g_features.insert(f);
    *out = &f->handle;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_CreateFeature(NrVkCommandBuffer cmd, NVSDK_NGX_Feature featureId,
                                                          NVSDK_NGX_Parameter* params,
                                                          NVSDK_NGX_Handle** out) {
    return NVSDK_NGX_VULKAN_CreateFeature1(g_vk_device, cmd, featureId, params, out);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_ReleaseFeature(NVSDK_NGX_Handle* handle) {
    std::lock_guard<std::mutex> guard(g_feature_lock);
    NgxFeature* f = live(handle);
    if (!f) return NVSDK_NGX_Result_FAIL_FeatureNotFound;
    g_features.erase(f);
    if (f->foreign) forwarder().vk_release(f->foreign);
    else if (f->model) nr::dlssnr::release_vk(f->model);
    delete f;
    return NVSDK_NGX_Result_Success;
}

// The resources arrive as NVSDK_NGX_Resource_VK* through the void-pointer overload
// (DlssNrFeature_Vk_Model.cpp:145 says so out loud), always the ImageViewInfo arm, never BufferInfo.
//
// LAYOUTS -- the one thing NVSDK_NGX_Resource_VK does not carry, so it is read from the caller's own
// source rather than asked for, and flagged in the report:
//   input  VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL   DlssNrFeature_Vk.cpp:439
//   output VK_IMAGE_LAYOUT_GENERAL                    DlssNrFeature_Vk.cpp:440, restored on the way out
//   depth and motion are the game's own and are never transitioned by the caller at all; they are
//   read as SHADER_READ_ONLY_OPTIMAL, which is what a sampled guide is in every path that reaches
//   here. A game that left one in GENERAL would produce a validation-layer complaint, not a wrong
//   picture.
NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_EvaluateFeature(NrVkCommandBuffer cmd,
                                                            const NVSDK_NGX_Handle* handle,
                                                            const NVSDK_NGX_Parameter* params, void*) {
    std::unique_lock<std::mutex> guard(g_feature_lock);
    NgxFeature* f = live(handle);
    if (!f) return NVSDK_NGX_Result_FAIL_FeatureNotFound;
    if (!cmd) return NVSDK_NGX_Result_FAIL_InvalidParameter;

    const Reader r(params);
    unsigned int width = f->width, height = f->height;
    r.uint("DLSSNR.Width", &width);
    r.uint("DLSSNR.Height", &height);
    read_controls(r, &f->controls);
    const nr::dlssnr::Controls6 controls = f->controls;

    void* color = r.resource("DLSSNR.Color");
    void* depth = r.resource("DLSSNR.Depth");
    void* motion = r.resource("DLSSNR.MVec");
    void* output = r.resource("DLSSNR.Output");

    nr::dlssnr::Rect depth_rect{}, motion_rect{};
    r.uint("DLSSNR.DepthSubrectBaseX", &depth_rect.x);
    r.uint("DLSSNR.DepthSubrectBaseY", &depth_rect.y);
    r.uint("DLSSNR.DepthSubrectWidth", &depth_rect.width);
    r.uint("DLSSNR.DepthSubrectHeight", &depth_rect.height);
    r.uint("DLSSNR.MVecSubrectBaseX", &motion_rect.x);
    r.uint("DLSSNR.MVecSubrectBaseY", &motion_rect.y);
    r.uint("DLSSNR.MVecSubrectWidth", &motion_rect.width);
    r.uint("DLSSNR.MVecSubrectHeight", &motion_rect.height);
    unsigned int sub = 0;
    if (r.uint("DLSSNR.ColorSubrectWidth", &sub) && sub) width = sub;
    if (r.uint("DLSSNR.ColorSubrectHeight", &sub) && sub) height = sub;

    unsigned int depth_inverted = 0, reset = 0;
    r.uint("DLSSNR.DepthInverted", &depth_inverted);
    r.uint("DLSSNR.Reset", &reset);
    float mv_x = 1.0f, mv_y = 1.0f;
    r.real("DLSSNR.MVecScaleX", &mv_x);
    r.real("DLSSNR.MVecScaleY", &mv_y);

    nr::dlssnr::Feature* model = f->model;
    void* foreign = f->foreign;
    guard.unlock();

    const int result =
        foreign ? forwarder().vk_evaluate(cmd, foreign, const_cast<NVSDK_NGX_Parameter*>(params), color,
                                          depth, motion, output, width, height, depth_rect.width,
                                          depth_rect.height, motion_rect.width, motion_rect.height,
                                          depth_rect.x, depth_rect.y, motion_rect.x, motion_rect.y,
                                          static_cast<int>(depth_inverted), static_cast<int>(reset),
                                          controls.intensity, controls.style, controls.local_structure,
                                          controls.local_tone, controls.skin_structure,
                                          controls.use_auto_mask, mv_x, mv_y)
                : nr::dlssnr::evaluate_vk(cmd, model, const_cast<NVSDK_NGX_Parameter*>(params), color,
                                          depth, motion, output, width, height, depth_rect, motion_rect,
                                          static_cast<int>(depth_inverted), static_cast<int>(reset),
                                          controls, mv_x, mv_y);

    // The Vulkan model answers -1 for "bad arguments or not an image view"; everything else is an NGX
    // code already.
    if (result == -1) return NVSDK_NGX_Result_FAIL_InvalidParameter;
    return static_cast<NVSDK_NGX_Result>(result);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_GetFeatureRequirements(NrVkInstance, NrVkPhysicalDevice,
                                                                   const void* info, void* OutSupported) {
    const bool nr = discovery_feature_id(info) == NVSDK_NGX_Feature_NeuralRendering;
    write_requirement(OutSupported, nr);
    return nr ? NVSDK_NGX_Result_Success : NVSDK_NGX_Result_FAIL_FeatureNotSupported;
}

// No instance or device extension is required, because no feature here runs. Writing zero and
// leaving the pointer alone is the "nothing needed" answer; a caller that iterates the array will
// iterate nothing.
NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_GetFeatureInstanceExtensionRequirements(
    const void*, uint32_t* OutExtensionCount, void** OutExtensionProperties) {
    if (OutExtensionCount) *OutExtensionCount = 0;
    if (OutExtensionProperties) *OutExtensionProperties = nullptr;
    return NVSDK_NGX_Result_Success;
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_GetFeatureDeviceExtensionRequirements(
    NrVkInstance, NrVkPhysicalDevice, const void*, uint32_t* OutExtensionCount,
    void** OutExtensionProperties) {
    if (OutExtensionCount) *OutExtensionCount = 0;
    if (OutExtensionProperties) *OutExtensionProperties = nullptr;
    return NVSDK_NGX_Result_Success;
}

// The legacy shape of the same question: four out-parameters rather than two calls.
NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_VULKAN_RequiredExtensions(unsigned int* OutInstanceExtCount,
                                                               const char*** OutInstanceExts,
                                                               unsigned int* OutDeviceExtCount,
                                                               const char*** OutDeviceExts) {
    if (OutInstanceExtCount) *OutInstanceExtCount = 0;
    if (OutInstanceExts) *OutInstanceExts = nullptr;
    if (OutDeviceExtCount) *OutDeviceExtCount = 0;
    if (OutDeviceExts) *OutDeviceExts = nullptr;
    return NVSDK_NGX_Result_Success;
}

// ---------------------------------------------------------------------------------------------
// API-independent
// ---------------------------------------------------------------------------------------------

// NVNGXProxy resolves this as `uint32_t (*)(void)`. Nothing in OptiScaler consumes it -- the only
// mention outside the proxy is a commented-out declaration in inputs/NVNGX.cpp -- so it exists to be
// resolvable. The value is the SDK version this core speaks, which is the one everything else here
// is written against.
NR_EXPORT uint32_t NVSDK_NGX_GetSnippetVersion(void) {
    return static_cast<uint32_t>(NVSDK_NGX_Version_API);
}

NR_EXPORT NVSDK_NGX_Result NVSDK_NGX_UpdateFeature(const void*, const NVSDK_NGX_Feature) {
    return NVSDK_NGX_Result_FAIL_FeatureNotSupported;
}

// ---------------------------------------------------------------------------------------------
// The DLSS gating finding, verified against OptiScaler's source rather than assumed.
//
// Question: with this core present and initialised, can OptiScaler decide real DLSS is available and
// stop using its own upscaler?  No, and not because of anything written above.
//
// 1. inputs/NVNGX_DLSS_Dx12.cpp GetUpscalerBackend (line ~598):
//
//        if (NVNGXProxy::IsDx12Inited() && primaryGpu.dlssCapable)  upscaler = Upscaler::DLSS;
//        if (primaryGpu.fsr4Support != FSR4Support::None)           upscaler = Upscaler::FFX;
//        if (Config::Instance()->Dx12Upscaler.has_value())          upscaler = Config...value();
//
//    Our Init_Ext returning Success does set IsDx12Inited(). The conjunction still needs dlssCapable.
//
// 2. misc/IdentifyGpu.cpp line 293:
//
//        gpuInfo.dlssCapable = gpuInfo.nvidiaArchInfo.architecture_id >= NV_GPU_ARCHITECTURE_TU100;
//
//    and nvidiaArchInfo is filled by NvAPI_GPU_GetArchInfo on a physical GPU handle found by matching
//    the adapter's LUID through NvAPI_SYS_GetLogicalGPUs. That is the real nvapi64.dll talking to a
//    real NVIDIA device. On an AMD card the handle is never found, the struct stays zero, and
//    dlssCapable is false. It is not read from NGX, from this core, or from any capability block, so
//    nothing this file does can move it.
//
// 3. The capability defaults above are therefore belt, not braces -- and on the path a *game* sees
//    they are immediately overwritten: inputs/NVNGX_DLSS_Dx12.cpp forwards the game's
//    GetCapabilityParameters to us and then calls InitNGXParameters on the block we returned, whose
//    very first line is `InParams->Set(NVSDK_NGX_Parameter_SuperSampling_Available, 1)`. OptiScaler
//    deliberately tells the game DLSS is available so the game asks for it and OptiScaler can
//    substitute FSR/XeSS. Fighting that would break the thing we are trying to add to.
//
//    Only OptiScaler's own DLSS-NR code reads our block without that overwrite, and it reads nothing
//    from it but the float-slot probe.
// ---------------------------------------------------------------------------------------------

BOOL APIENTRY DllMain(HMODULE module, DWORD reason, LPVOID reserved) {
    (void) reserved;
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(module);
        // The model loads its SPIR-V and its ~290 MB of weights from build/ and artifacts/ beside the
        // module that owns it, and writes dlssnr-amd.log there too -- the same rule every other DLL in
        // this project follows, and the reason none of them needs a path configured.
        nr::pe::set_module(module);
        nr::pe::install_crash_watch();
        // Vulkan is resolved at run time rather than imported; see the note in
        // windows/build/build_optiscaler_nr.sh on why a static import of vulkan-1.dll kills games.
        nr_vk_load();
        // Which build this is, in the first line of the log. Asked once too often:
        // "is the fix in the DLL you are running" has no answer without it.
#ifndef NR_BUILD_STAMP
#define NR_BUILD_STAMP "unstamped"
#endif
        // Under its own file name: the packages ship it as dlssnr_core.dll (never NVIDIA's _nvngx.dll).
        char path[MAX_PATH] = {};
        const DWORD n = GetModuleFileNameA(module, path, MAX_PATH);
        const char* name = n ? path : "NGX core";
        for (const char* c = path; n && *c; ++c)
            if (*c == '\\' || *c == '/') name = c + 1;
        nr::pe::log("[nr] %s attached (build %s, %s %s), log %s", name, NR_BUILD_STAMP,
                    __DATE__, __TIME__, nr::pe::log_path());
        // [Network] ACO Mode: decided before any device of ours (or a game's we add features to) is made.
        nr::pe::configure_network(nr::pe::module_folder());
        // OptiScaler loads this module during its own initialisation, before any Vulkan device
        // exists: the one moment its device hook can still be corrected. See nr_pe_optifix.hpp.
        nr::pe::fix_optiscaler();
    }
    return TRUE;
}
